### ISSUE TITLE
Schillings.SwordPhish.v1.0.x86.msi not installing

### ISSUE THREAD

**Issue by ModernAesthetics** [Schillings/SwordPhish#2]
Does not seem to install on Office 365 Business Version 1711 (Build 8730.2127 Click-to-Run)

**Comment by eth0izzle** [comment]
Thanks @ModernAesthetics. Do you get any errors? All pre-reqs installed? Can you paste your MSI installer log please (run msiexec with /v /x).

**Comment by eth0izzle** [comment]
Hi @ModernAesthetics, did you manage to get it installed?

**Comment by thfadmin** [comment]
same here. Log below. 

=== Logging started: 1/15/2018  11:12:39 ===
Action 11:12:39: INSTALL. 
Action start 11:12:39: INSTALL.
Action 11:12:39: FindRelatedProducts. Searching for related applications
Action start 11:12:39: FindRelatedProducts.
Action ended 11:12:39: FindRelatedProducts. Return value 1.
Action 11:12:39: PrepareDlg. 
Action start 11:12:39: PrepareDlg.
Info 2898.For WixUI_Font_Normal textstyle, the system created a 'Tahoma' font, in 0 character set, of 13 pixels height.
Info 2898.For WixUI_Font_Bigger textstyle, the system created a 'Tahoma' font, in 0 character set, of 19 pixels height.
Action 11:12:39: PrepareDlg. Dialog created
Action ended 11:12:39: PrepareDlg. Return value 1.
Action 11:12:39: AppSearch. Searching for installed applications
Action start 11:12:39: AppSearch.
Action ended 11:12:39: AppSearch. Return value 1.
Action 11:12:39: LaunchConditions. Evaluating launch conditions
Action start 11:12:39: LaunchConditions.
Action ended 11:12:39: LaunchConditions. Return value 1.
Action 11:12:39: ValidateProductID. 
Action start 11:12:39: ValidateProductID.
Action ended 11:12:39: ValidateProductID. Return value 1.
Action 11:12:39: CostInitialize. Computing space requirements
Action start 11:12:39: CostInitialize.
Action ended 11:12:39: CostInitialize. Return value 1.
Action 11:12:39: FileCost. Computing space requirements
Action start 11:12:39: FileCost.
Action ended 11:12:39: FileCost. Return value 1.
Action 11:12:39: CostFinalize. Computing space requirements
Action start 11:12:39: CostFinalize.
Action ended 11:12:39: CostFinalize. Return value 1.
Action 11:12:39: MigrateFeatureStates. Migrating feature states from related applications
Action start 11:12:39: MigrateFeatureStates.
Action ended 11:12:39: MigrateFeatureStates. Return value 0.
Action 11:12:39: WelcomeDlg. 
Action start 11:12:39: WelcomeDlg.
Action 11:12:39: WelcomeDlg. Dialog created
Info 2898.For WixUI_Font_Title textstyle, the system created a 'Tahoma' font, in 0 character set, of 14 pixels height.
Action 11:12:41: OptionsDialog. Dialog created
Action 11:12:48: OptionsCustomAction. 
Action start 11:12:48: OptionsCustomAction.
Action ended 11:12:48: OptionsCustomAction. Return value 3.
DEBUG: Error 2896:  Executing action OptionsCustomAction failed.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2896. The arguments are: OptionsCustomAction, , 
Action ended 11:12:48: WelcomeDlg. Return value 3.
Action 11:12:48: FatalError. 
Action start 11:12:48: FatalError.
Action 11:12:48: FatalError. Dialog created
Action ended 11:12:49: FatalError. Return value 2.
Action ended 11:12:49: INSTALL. Return value 3.
Property(C): UpgradeCode = {6B5DFDC5-F72E-4301-A361-90915BD24781}
Property(C): VSTOR40 = #1
Property(C): NETFRAMEWORK40CLIENT = #1
Property(C): INSTALLFOLDER = C:\Program Files (x86)\Schillings\
Property(C): PRODUCTFOLDER = C:\Program Files (x86)\Schillings\SwordPhish\
Property(C): WixUIRMOption = UseRM
Property(C): WIXUI_INSTALLDIR = PRODUCTFOLDER
Property(C): RECIPIENTPROPERTY = ######@firm.com (edited)
Property(C): SUBJECTPROPERTY = SwordPhish Report
Property(C): ACTIONPROPERTY = 0
Property(C): ALLUSERS = 1
Property(C): ARPNOMODIFY = 1
Property(C): ProgramFilesFolder = C:\Program Files (x86)\
Property(C): TARGETDIR = F:\
Property(C): SourceDir = F:\Downloads\
Property(C): ARPPRODUCTICON = icon.ico
Property(C): Manufacturer = Schillings International LLP
Property(C): ProductCode = {B5E0D66F-F946-4A66-BE37-DEA0EE6BE482}
Property(C): ProductLanguage = 1033
Property(C): ProductName = Schillings SwordPhish
Property(C): ProductVersion = 1.5.0.0
Property(C): DefaultUIFont = WixUI_Font_Normal
Property(C): WixUI_Mode = InstallDir
Property(C): ErrorDialog = ErrorDlg
Property(C): SecureCustomProperties = ACTIONPROPERTY;NETFRAMEWORK40CLIENT;RECIPIENTPROPERTY;SUBJECTPROPERTY;WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED
Property(C): MsiLogFileLocation = C:\Users\EYEINT~1.SKY\AppData\Local\Temp\MSI3aad4.LOG
Property(C): PackageCode = {B70E5669-D95A-415B-B0F4-F8CF72CC001C}
Property(C): ProductState = -1
Property(C): PackagecodeChanging = 1
Property(C): CURRENTDIRECTORY = F:\Downloads
Property(C): CLIENTUILEVEL = 0
Property(C): CLIENTPROCESSID = 6348
Property(C): VersionDatabase = 200
Property(C): VersionMsi = 5.00
Property(C): VersionNT = 603
Property(C): ACTION = INSTALL
Property(C): VersionNT64 = 603
Property(C): WindowsBuild = 9600
Property(C): ServicePackLevel = 0
Property(C): ServicePackLevelMinor = 0
Property(C): MsiNTProductType = 1
Property(C): WindowsFolder = C:\Windows\
Property(C): WindowsVolume = C:\
Property(C): System64Folder = C:\Windows\system32\
Property(C): SystemFolder = C:\Windows\SysWOW64\
Property(C): RemoteAdminTS = 1
Property(C): TempFolder = C:\Users\EYEINT~1.SKY\AppData\Local\Temp\
Property(C): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(C): ProgramFiles64Folder = C:\Program Files\
Property(C): CommonFiles64Folder = C:\Program Files\Common Files\
Property(C): AppDataFolder = C:\Users\eye.in.the.sky\AppData\Roaming\
Property(C): FavoritesFolder = C:\Users\eye.in.the.sky\Favorites\
Property(C): NetHoodFolder = C:\Users\eye.in.the.sky\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(C): PersonalFolder = C:\Users\eye.in.the.sky\Documents\
Property(C): PrintHoodFolder = C:\Users\eye.in.the.sky\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(C): RecentFolder = C:\Users\eye.in.the.sky\AppData\Roaming\Microsoft\Windows\Recent\
Property(C): SendToFolder = C:\Users\eye.in.the.sky\AppData\Roaming\Microsoft\Windows\SendTo\
Property(C): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(C): CommonAppDataFolder = C:\ProgramData\
Property(C): LocalAppDataFolder = C:\Users\eye.in.the.sky\AppData\Local\
Property(C): MyPicturesFolder = C:\Users\eye.in.the.sky\Pictures\
Property(C): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(C): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(C): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(C): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(C): DesktopFolder = C:\Users\Public\Desktop\
Property(C): FontsFolder = C:\Windows\Fonts\
Property(C): GPTSupport = 1
Property(C): OLEAdvtSupport = 1
Property(C): ShellAdvtSupport = 1
Property(C): MsiAMD64 = 6
Property(C): Msix64 = 6
Property(C): Intel = 6
Property(C): PhysicalMemory = 8145
Property(C): VirtualMemory = 1461
Property(C): LogonUser = ########
Property(C): UserSID = S-1-5-21-3819166441-2393116361-308483194-2148
Property(C): UserLanguageID = 1033
Property(C): ComputerName = WSADMIN
Property(C): SystemLanguageID = 1033
Property(C): ScreenX = 1920
Property(C): ScreenY = 1080
Property(C): CaptionHeight = 23
Property(C): BorderTop = 1
Property(C): BorderSide = 1
Property(C): MsiTabletPC = 1
Property(C): TextHeight = 16
Property(C): TextInternalLeading = 3
Property(C): ColorBits = 32
Property(C): TTCSupport = 1
Property(C): Time = 11:12:49
Property(C): Date = 1/15/2018
Property(C): MsiNetAssemblySupport = 4.7.2558.0
Property(C): MsiWin32AssemblySupport = 6.3.9600.17415
Property(C): RedirectedDllSupport = 2
Property(C): AdminUser = 1
Property(C): Privileged = 1
Property(C): USERNAME = 
Property(C): DATABASE = F:\Downloads\Schillings.SwordPhish.v1.0.x86.msi
Property(C): OriginalDatabase = F:\Downloads\Schillings.SwordPhish.v1.0.x86.msi
Property(C): SOURCEDIR = F:\Downloads\
Property(C): VersionHandler = 5.00
Property(C): UILevel = 5
Property(C): EXECUTEACTION = INSTALL
Property(C): ROOTDRIVE = F:\
Property(C): CostingComplete = 1
Property(C): OutOfDiskSpace = 0
Property(C): OutOfNoRbDiskSpace = 0
Property(C): PrimaryVolumeSpaceAvailable = 0
Property(C): PrimaryVolumeSpaceRequired = 0
Property(C): PrimaryVolumeSpaceRemaining = 0
Property(C): INSTALLLEVEL = 1
=== Logging stopped: 1/15/2018  11:12:49 ===
MSI (c) (CC:6C) [11:12:49:440]: Product: Schillings SwordPhish -- Installation failed.

MSI (c) (CC:6C) [11:12:49:440]: Windows Installer installed the product. Product Name: Schillings SwordPhish. Product Version: 1.5.0.0. Product Language: 1033. Manufacturer: Schillings International LLP. Installation success or error status: 1603.

**Comment by eth0izzle** [comment]
How are you running the installer? GUI or via cmdline? Sounds ridiculous but running msiexec in power shell doesn’t seem to work.

**Comment by thfadmin** [comment]
Gui

**Comment by eth0izzle** [comment]
I think I know the issue. Could you try installing via cmdline please (as sampled in the README) and let me know if his works. Otherwise I will push a patch tomorrow.

**Comment by thfadmin** [comment]
That did install successfully. Thanks

**Comment by eth0izzle** [comment]
@thfadmin @ModernAesthetics I've just pushed 3 new [releases](https://github.com/Schillings/SwordPhish/releases). If you are installing on end user machines just run the .exe, if you are pushing out via GPO then use the MSIs for your platform (x86/x64).

**Comment by GigglySysadmin** [comment]
I got this when _not_ specifying the SUBJECTPROPERTY.  I have to use the MSI method because the EXE detects and installs the 64-bit on a 64-bit OS but most clients I mess with are 32-bit so do not recognize the add-in.
