### ISSUE TITLE
msiexec error

### ISSUE THREAD

**Issue by passwordleak** [Schillings/SwordPhish#3]
"This installation package could not be opened. Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package. "

I've used the following commands as admin, and they result in the same error: 
`msiexec /i Schillings.SwordPhish.Installer.msi RECIPIENTPROPERTY="reports@mysoc.com" ACTIONPROPERTY=2
msiexec /i .\Schillings.SwordPhish.v1.0.x86.msi RECIPIENTPROPERTY="reports@mysoc.com" SUBJECTPROPERTY="Phishing Report" ACTIONPROPERTY=1
`

However, I have been able to install it and use it using the GUI, so I know it works.

**Comment by eth0izzle** [comment]
If the GUI works this should work. What system are you on?

Sounds silly but try removing the `.\`, i.e. `msiexec /i "Schillings.SwordPhish.v1.0.x86.msi" RECIPIENTPROPERTY="reports@mysoc.com" SUBJECTPROPERTY="Phishing Report" ACTIONPROPERTY=1`

**Comment by passwordleak** [comment]
OK, It works in CMD, but not powershell for some reason. However, in powershell, I got it to work by using
`cmd /c 'msiexec /i "Schillings.SwordPhish.v1.0.x86.msi" RECIPIENTPROPERTY="reports@mysoc.com" SUBJECTPROPERTY="Phishing Report" ACTIONPROPERTY=1'`

**Comment by eth0izzle** [comment]
Interesting- thanks @passwordleak!
