### ISSUE TITLE
I can't enable the add-in in Outlook

### ISSUE THREAD

**Issue by ruboncio** [Schillings/SwordPhish#4]
Hi,
We have installed this add-in in our company, it gets install properly, but when you open Outlook it doesn't let you enable it. It comes up in the Add-in screen, you click in go, enable... but nothing happens.

Any idea? We are not missing any of the requirements. Framework and VSO are installed.  

Thanks

**Comment by eth0izzle** [comment]
Can you try https://help.yesware.com/hc/en-us/articles/229940987-Re-enabling-a-disabled-add-in-for-Outlook-2016-2013-and-2010

What Outlook/Windows are you running?

**Comment by ruboncio** [comment]
Hi, 
We already tried that and it doesn't make anything. It stays disabled no matters what.
We're running:
-Win10 64bits 1709 (10.0.15063 Build 15063)
-Outlook is Office 365 Business x64 (Version 1711 - Build 8730.2175 Click-to-Run)

**Comment by eth0izzle** [comment]
@ruboncio I've just pushed 3 new [releases](https://github.com/Schillings/SwordPhish/releases). If you are installing on end user machines just run the .exe, if you are pushing out via GPO then use the MSIs for your platform (x86/x64).

**Comment by ruboncio** [comment]
@eth0izzle Thanks! It seems to be working when I run the .exe manually.
Do the switches work for the .exe in the same way as they do for .msi?
RECIPIENTPROPERTY="csirt@opus2.com" ACTIONPROPERTY=1  ?

Does the /qn work for the .exe?

Thanks

**Comment by eth0izzle** [comment]
No the switches don't work for the .exe - just the MSIs. The .exe is more for end users, and options can be configured in the installers GUI. If you need to pass in any options use the MSI for your platform.

**Comment by ruboncio** [comment]
Yeah, the problem we have a mix of Office 32/64 installations, and we deploy using InTune. 
I'm playing with InTune right now.. 

Thanks for the new release!

**Comment by eth0izzle** [comment]
@ruboncio you're welcome!

I don't want to build up a comprehensive list of different deployment options, but it would be good to collate simple overviews of what's required for the most popular MDMs/systems management tools. Would you mind sharing your experiences of deploying with TuneIn?

**Comment by ruboncio** [comment]
Hi, sorry for my late reply. I was on annual leave.
**On machine itself:**
-If I install via .exe it works... 
-Using a batch file or trying to use CLI - /quiet upon the .msi files x86/x64, doesn't install at all.
Not sure why yet. I need to check event logs  
**On InTune**
Haven't managed to make it work yet.
