### ISSUE TITLE
64 bit Outlook - addin not working

### ISSUE THREAD

**Issue by CyberDelight** [Schillings/SwordPhish#5]
Hi,

Thank you very much for the contribution. I have successfully installed it on windows 10/windows 7 machines running office 32 bit. Following the same steps and using the MSI, the add-in is not visible/installed on the 64bit outlook client. When clicking on the vsto file directly the add-in does install and become visible in the outlook bar, but it does not give the opportunity to report anything (not enabled???). Perhaps there is a registry setting missing for 64bit outlook clients?

Would you be able to point me in the right direction on how to install this on a 64-bit machine?

In advance many thanks!

**Comment by eth0izzle** [comment]
Thanks for the report. Does the machine with 64bit Outlook also have the 32bit version installed?

**Comment by CyberDelight** [comment]
No it only has the 64bit Outlook version installed. I have tried it on different machines with 64bit version of outlook installed with the same results. On 32bit outlook versions it's working fine without issues.

**Comment by eth0izzle** [comment]
Interesting. Can you check HKLM\SOFTWARE\Schillings\SwordPhish and HKLM\SOFTWARE\ Wow6432Node\Schillings\SwordPhish - does any keys exist?

**Comment by CyberDelight** [comment]
The HKLM\SOFTWARE\Schillings\SwordPhish key exist , however the HKLM\SOFTWARE\ Wow6432Node\Schillings\SwordPhish does not seem to exist

**Comment by eth0izzle** [comment]
That is correct - are there values inside the key, i.e. `ReportRecipient`?

So just to confirm

* MSI installation did NOT work
* You manually installed using the .VTSO
* Button appears in Outlook but doesn't do anything when clicked

I've just tested on a 64bit Windows 10 and 64bit Office 2016 and it's working as expected.

Can you provide me some version numbers please and I'll see what's going on.

**Comment by CyberDelight** [comment]
Strange, below the answers:
•MSI installation did NOT work - CORRECT
•You manually installed using the .VTSO - CORRECT
•Button appears in Outlook but doesn't do anything when clicked -CORRECT

This is the test run so far:
Outlook 2013 (15.0.4971.100) 32-bit  Result : Works fine
Outlook 2016 (16.0.4549.1000) 64-BIT Result: MSI installation did NOT work / Manually installed VSTO, button does not respond.

**Comment by eth0izzle** [comment]
@CyberDelight I've pushed 3 new [releases](https://github.com/Schillings/SwordPhish/releases). If you are installing on end user machines just run the .exe, if you are pushing out via GPO then use the MSIs for your platform (x86/x64).
